services:
  obuilder:
    container_name: obuilder
    build: .
    ports:
      - '80:3000'
    environment:
      - NODE_ENV='staging'
      - LTO_NODE='https://testnet.lto.network'
      - LTO_NETWORK_ID='T'
      - IPFS_START='false'
      - REACT_APP_RELAY='https://relay.lto.network'
