services:
  ownable-generator:
    container_name: ownable-generator
    build: .
    volumes:
      - ownable-generator-storage:/storage
    ports:
      - "3000:3000"  

volumes:
  ownable-generator-storage:
